# Generated by Django 6.0.6 on 2026-06-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_ddcetquestion_correct_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ddcetquestion',
            name='option_a_guj',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ddcetquestion',
            name='option_b_guj',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ddcetquestion',
            name='option_c_guj',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ddcetquestion',
            name='option_d_guj',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ddcetquestion',
            name='question_text_guj',
            field=models.TextField(blank=True, null=True),
        ),
    ]
