# Generated by Django 6.0.6 on 2026-06-10 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_ddcetquestion_option_a_guj_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examresult',
            old_name='date_taken',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='correct_answers',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='total_questions',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='wrong_answers',
        ),
    ]
