# Generated by Django 6.0.6 on 2026-06-10 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_rename_date_taken_examresult_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='correct_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examresult',
            name='skipped_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examresult',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examresult',
            name='wrong_answers',
            field=models.IntegerField(default=0),
        ),
    ]
